# Week1 Day2

## 1. Python basic operations

## 2. Linear Algebra basic operations

### 2.1 Vector Operations

create a vector:
$v = \begin{equation}
    \left[ \begin{array}{c}
         1  \\
         2 \\
         3
    \end{array}
    \right]
\end{equation}$

In [1]:
import numpy as np
# method with list
v1 = [1,2,3]
v1 = np.array([v1]).T
print(v1)

[[1]
 [2]
 [3]]


In [2]:
# method with numpy
v2 = np.array([[1],[2],[3]])
print(v2)

[[1]
 [2]
 [3]]


In [5]:
# creating a 1-D list(Horizontal)
list1=[1,2,3]
# creating a 1-D list(Vertical)
list2=[[1],[2],[3]]
print(list1)
print(list2)

# creating a vector1 as row vector
vector1=np.array(list1)
# creating a vector2 as column vector
vector2=np.array(list2)

print("Horizontal Vector")
print(vector1)
print("-----------------")
print("Vertical vector")
print(vector2)

[1, 2, 3]
[[1], [2], [3]]
Horizontal Vector
[1 2 3]
-----------------
Vertical vector
[[1]
 [2]
 [3]]


In [10]:
print(v1)
print(v2)
v = v1+v2
print(v)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[2]
 [4]
 [6]]


In [7]:
print(3*v)

[[ 6  9 12]
 [ 9 12 15]
 [12 15 18]]


### 2.2 Matrix Operations

#### **Task** Create a matrix:

$M = \begin{equation}
    \left[ \begin{array}{ccc}
         1&4&7  \\
         2&5&8 \\
         3&6&9
    \end{array}
    \right]
\end{equation}$

In [12]:
# with the method of list
# TODO
M = [[1,4,7],[2,5,8],[3,6,9]]
M=np.array([M]).T
print(M)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [13]:
# with the method of array
# TODO 
M = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(M)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### **Task** Matrix indexing
get the result by indexing M:
$v = \begin{equation}
    \left[ \begin{array}{cc}
         4&7  \\
         5&8
    \end{array}
    \right]
\end{equation}$

In [15]:
# TODO
M2 = np.array([[4,7],[5,8]])
print(M2)
M3=print(M[0:2,1:3])

[[4 7]
 [5 8]]
[[4 7]
 [5 8]]


### 2.3 Many other functions for creating matrices/vectors provided Numpy

In [16]:
a = np.zeros((2,3)) # create an array with all zeros
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
b = np.ones((1,2)) # create an array with all ones
print(b)

[[1. 1.]]


In [18]:
c = np.full((2,4), 7) # create an array with constant values
print(c)

[[7 7 7 7]
 [7 7 7 7]]


In [19]:
d = np.eye(3) # create a 3 by 3 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2.4 Multiplications

#### 2.4.1 Dot Multiplication

In [20]:
np.dot(3, 4)

12

$M = \begin{equation}
    \left[ \begin{array}{ccc}
         1&4&7  \\
         2&5&8 \\
         3&6&9
    \end{array}
    \right]
\end{equation}$
$v = \begin{equation}
    \left[ \begin{array}{c}
         2  \\
         4 \\
         6
    \end{array}
    \right]
\end{equation}$

In [21]:
# method 1
M.dot(v)

array([[60],
       [72],
       [84]])

In [22]:
# method 2
np.dot(M,v)

array([[60],
       [72],
       [84]])

#### 2.4.2 Element-wise Multiplication

In [23]:
np.multiply(M,v)

array([[ 2,  8, 14],
       [ 8, 20, 32],
       [18, 36, 54]])

In [24]:
np.multiply(v,v)

array([[ 4],
       [16],
       [36]])

In [25]:
np.multiply(M,M)

array([[ 1, 16, 49],
       [ 4, 25, 64],
       [ 9, 36, 81]])

#### 2.4.3 Inner(dot) or Outer(cross) product

 **dot/inner product of two vectors**

In [30]:
a = np.array([1,2,3])
b = np.array([0,1,0])
print('a:',a)
print('b:',b)
np.inner(a, b)

a: [1 2 3]
b: [0 1 0]


2

**inner product multidimensional example**

In [27]:
# eg.1
a = np.array([[1,2,3],[4,5,6]])
b = np.array([0,1,0])
print('a:',a)
print('b:',b)
print(np.inner(a, b))

a: [[1 2 3]
 [4 5 6]]
b: [0 1 0]
[2 5]


In [28]:
# eg.2 (tensor)
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
print('a:',a)
print('b:',b)
print(np.inner(a,b))

a: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b: [0 1 2 3]
[[ 14  38  62]
 [ 86 110 134]]


**outer product**

In [29]:
a = np.ones((5,))
b = np.linspace(-2, 2, 5)
print('a:',a)
print('b:',b)
print(np.outer(a,b))

a: [1. 1. 1. 1. 1.]
b: [-2. -1.  0.  1.  2.]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### 2.4.4 Matrix product of two arrays

In [31]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
c = np.array([1, 2])

In [32]:
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [33]:
np.matmul(a,c)

array([1, 2])

### 2.5 Properties

#### 2.5.1 Transpose

In [35]:
print(M)
print(M.T)
print(v)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [4]
 [6]]


In [36]:
print(v)
print(v.T)

[[2]
 [4]
 [6]]
[[2 4 6]]


In [37]:
print(M.shape)
print(M.T.shape)
print(v.shape)
print(v.T.shape)

(3, 3)
(3, 3)
(3, 1)
(1, 3)


#### 2.5.2 Matrix Determinant

In [38]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

#### 2.5.3 Matrix Inverse

In [39]:
from numpy.linalg import inv

a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)

In [40]:
print('a:',a)
print('inv:',ainv)

a: [[1. 2.]
 [3. 4.]]
inv: [[-2.   1. ]
 [ 1.5 -0.5]]


#### 2.5.4 Eigenvalues and Eigenvectors

In [44]:
from numpy import linalg as LA
print(np.diag((1,2,3)))
w, v = LA.eig(np.diag((1, 2, 3)))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [42]:
w

array([1., 2., 3.])

In [43]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 2.6 Arithmetic operators including addition +, subtraction -, multiplication *, division / and exponentiation ** are applied to arrays elementwise.

In [45]:
A = np.array([[3,1],[2,-1]])
B = np.array([[2,-2],[5,1]])
print(A)
print(B)

[[ 3  1]
 [ 2 -1]]
[[ 2 -2]
 [ 5  1]]


In [46]:
A * B

array([[ 6, -2],
       [10, -1]])

In [47]:
A ** 2

array([[9, 1],
       [4, 1]], dtype=int32)

In Python 3.5+, the symbol @ computes matrix multiplication for NumPy arrays

In [48]:
A @ B

array([[11, -5],
       [-1, -5]])

Matrix powers are performed by the function numpy.linalg.matrix_power. It's a long function name and so it's convenient to import it with a shorter name:

In [49]:
from numpy.linalg import matrix_power as mpow

Compute $A^3$

In [53]:
print(mpow(A,2))
mpow(A,3)

[[11  2]
 [ 4  3]]


array([[37,  9],
       [18,  1]])

In [51]:
A @ A @ A

array([[37,  9],
       [18,  1]])

### 2.7 Others: Broadcasting

In [54]:
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + np.array([1,1,1,1,1])
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


In [55]:
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + 1
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


In [56]:
u = np.array([1,2,3,4])
print(u)

[1 2 3 4]


In [57]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
print(A)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [58]:
result = A + u
print(result)


[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
